# Generated by Django 4.2 on 2023-04-06 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_image_link', models.ImageField(blank=True, upload_to='cat_image')),
                ('cat_added_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(max_length=50)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.TextField()),
                ('sub_cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsapp.sub_category')),
            ],
        ),
    ]
