# Generated by Django 4.2 on 2023-04-19 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsapp.category')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsapp.sms')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsapp.sub_category')),
            ],
        ),
    ]
