# Generated by Django 4.2 on 2023-04-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lang',
            name='sms',
        ),
        migrations.RemoveField(
            model_name='lang',
            name='sub_category',
        ),
    ]
