# Generated by Django 4.2 on 2023-04-19 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_remove_lang_sms_remove_lang_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lang',
            old_name='lang_name',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='lang',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smsapp.lang'),
            preserve_default=False,
        ),
    ]
