# Generated by Django 4.2 on 2023-04-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='status',
        ),
        migrations.AddField(
            model_name='sms',
            name='sms_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='sms',
            field=models.TextField(),
        ),
    ]
