# Generated by Django 4.2 on 2023-04-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_remove_sms_status_sms_sms_status_alter_sms_sms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='sms_status',
            new_name='smsstatus',
        ),
    ]
