# Generated by Django 4.2 on 2023-04-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_alter_category_cat_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image_link',
            field=models.CharField(max_length=50),
        ),
    ]
