# Generated by Django 4.2 on 2023-04-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_rename_sms_status_sms_smsstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='smsstatus',
            new_name='status',
        ),
    ]
