# Generated by Django 4.2 on 2023-04-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_rename_smsstatus_sms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='max_complaints',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
