# Generated by Django 4.2 on 2023-04-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_alter_complaint_max_complaints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='max_complaints',
        ),
    ]
