# Generated by Django 4.2 on 2023-06-01 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_remove_category_language_category_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='language',
        ),
        migrations.AddField(
            model_name='lang',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userdata.category'),
            preserve_default=False,
        ),
    ]
