# Generated by Django 4.2 on 2023-04-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0009_alter_category_cat_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image_link',
            field=models.ImageField(blank=True, upload_to='cat_image'),
        ),
    ]
