# Generated by Django 4.2 on 2023-06-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0010_remove_lang_category_sub_category_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='language',
        ),
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userdata.lang'),
            preserve_default=False,
        ),
    ]
