# Generated by Django 4.2 on 2023-06-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0012_sms_dislikes_sms_likes_like_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='sms',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
