# Generated by Django 4.2 on 2023-06-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0013_remove_like_sms_remove_like_user_delete_dislike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='likes',
        ),
    ]
