# Generated by Django 4.2 on 2023-06-07 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userdata', '0014_remove_sms_dislikes_remove_sms_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_sms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sms',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_sms', to=settings.AUTH_USER_MODEL),
        ),
    ]
