# Generated by Django 4.2 on 2023-06-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0017_remove_category_language_delete_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='Sub_cat_image',
            field=models.ImageField(default='media/cat_image/qoutes.jpg', upload_to='Sub_cat_image'),
        ),
    ]
