# Generated by Django 4.2 on 2023-08-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0018_alter_sub_category_sub_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='title',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
