# Generated by Django 4.2 on 2023-06-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0018_alter_sub_category_sub_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='Sub_cat_image',
            field=models.ImageField(default='cat_image/qoutes.jpg', upload_to='Sub_cat_image'),
        ),
    ]
