# Generated by Django 4.2 on 2023-06-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0019_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
