# Generated by Django 4.2 on 2023-06-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0019_alter_sub_category_sub_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='Sub_cat_image',
            field=models.ImageField(default='Sub_cat_image/diamond.png', upload_to='Sub_cat_image'),
        ),
    ]
