# Generated by Django 4.2 on 2023-08-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0020_remove_sub_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='featureimage/')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.sub_category')),
            ],
        ),
    ]
