# Generated by Django 4.2 on 2023-08-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0021_sub_category_tital_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='tital_name',
            new_name='tital',
        ),
    ]
