# Generated by Django 4.2 on 2023-08-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0021_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(default=2, upload_to='featureimage/thumbnail'),
            preserve_default=False,
        ),
    ]
