# Generated by Django 4.2 on 2023-08-29 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0022_image_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker', models.ImageField(upload_to='sticker/')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.sub_category')),
            ],
        ),
    ]
