# Generated by Django 4.2 on 2023-08-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0022_rename_tital_name_sub_category_tital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='tital',
            new_name='title',
        ),
    ]
