# Generated by Django 4.2 on 2023-08-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0023_rename_tital_sub_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='title',
            new_name='sub_cat_title',
        ),
    ]
