# Generated by Django 4.2 on 2023-08-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0024_rename_title_sub_category_sub_cat_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='sub_cat_title',
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='sub_cat_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
